# Generated by Django 4.0.3 on 2022-04-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placestorest',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='placestorest',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='placestorest',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
