# Generated by Django 4.0.3 on 2022-05-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_rest', '0003_placestorest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=255)),
                ('request_date', models.DateTimeField()),
            ],
        ),
    ]
