# Generated by Django 4.0.3 on 2022-05-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_rest', '0004_usersactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersactivity',
            name='user_id',
        ),
    ]
